apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-auth-db
  labels:
    app: {{ .Release.Name }}-auth-db
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-auth-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-auth-db
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
        imagePullPolicy: {{ .Values.database.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.database.port }}
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.database.credentials.username }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.database.credentials.password }}"
        - name: POSTGRES_DB
          value: "{{ .Values.database.credentials.database }}"
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-auth-db-pvc
                        