apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-auth-db
  labels:
    app: {{ .Release.Name }}-auth-db
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-auth-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-auth-db
    spec:
      containers:
      - name: postgres
        image: "postgres:15"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "{{ .Values.database.credentials.username }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.database.credentials.password }}"
        - name: POSTGRES_DB
          value: "{{ .Values.database.credentials.database }}"
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi
