apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-auth-db-pvc
  labels:
    app: {{ .Release.Name }}-auth-db
spec:
  accessModes:
  - {{ .Values.database.persistence.accessMode | quote }}
  {{- if .Values.database.persistence.storageClass }}
  storageClassName: {{ .Values.database.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.database.persistence.size | quote }}