apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth-db
  labels:
    app: {{ .Release.Name }}-auth-db
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-auth-db
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres