apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth-db
  labels:
    app: {{ .Release.Name }}-auth-db
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-auth-db
  ports:
  - port: {{ .Values.database.port }}
    targetPort: {{ .Values.database.port }}
    protocol: TCP
    name: postgres