apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: {{ .Release.Name }}-auth-service
spec:
  selector:
    app: {{ .Release.Name }}-auth-service
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
