# Generated by Django 5.1.7 on 2025-04-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
