services:
  auth-service:
    image: auth-service:latest
    container_name: auth-service
    depends_on:
      - auth-db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://postgres:password@auth-db:5432/auth"
      JWT_SECRET: "super_strong_secret"
      HOST: "0.0.0.0"
    restart: always

  auth-db:
    image: postgres:15
    container_name: auth-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
