apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: api-gateway
  endpoints:
    - port: metrics
      path: /metrics
