# Generated by Django 5.1.7 on 2025-04-05 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.comment'),
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
