# Generated by Django 5.1.7 on 2025-04-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_attached_file_alter_comment_reply_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attached_file',
        ),
    ]
