replicaCount: 1
image:
  repository: api-gateway
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
env:
  AUTH_SERVICE_HOST: "auth-service"
  HOST: "0.0.0.0"
