apiVersion: v1
kind: Service
metadata:
  name: content-service
  labels:
    app: {{ .Release.Name }}-content-service
spec:
  selector:
    app: {{ .Release.Name }}-content-service
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
