# Generated by Django 5.1.7 on 2025-03-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_community_members'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(blank=True, to='user.user'),
        ),
    ]
