# Generated by Django 5.1.7 on 2025-03-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_community_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
