//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use schemars::JsonSchema;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, JsonSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_role")]
pub enum UserRole {
    #[sea_orm(string_value = "community_editor")]
    CommunityEditor,
    #[sea_orm(string_value = "community_viewer")]
    CommunityViewer,
    #[sea_orm(string_value = "events_editor")]
    EventsEditor,
    #[sea_orm(string_value = "events_viewer")]
    EventsViewer,
}
